version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "22"
    python: "3.13"
  jobs:
    post_install:
      - pip install poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install

mkdocs:
  configuration: mkdocs.yml
