[tool.poetry]
name = "multi-dimpy"
version = "0.1.0"
description = ""
authors = ["Nathan Schill <nateschill@gmail.com>"]
readme = "README.md"
packages = [{include = "multi_dimpy", from = "src"}]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
